name: movie
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.12.0 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.3.8

  salomon_bottom_bar: ^3.1.0
  dio: ^4.0.0
  cookie_jar: ^3.0.1
  dio_cookie_manager: ^2.0.0
  html: ^0.15.0

  webview_flutter: ^2.1.1
  
  flutter: 
    sdk: flutter
  equatable: ^2.0.3

dev_dependencies: 
  flutter_lints: ^1.0.0
  flutter_test: 
    sdk: flutter

  flutter_launcher_name:
    git:
      url: https://github.com/d1y/flutter_launcher_name

# flutter pub run flutter_launcher_name:main
flutter_launcher_name:
  name: "YY播放器"

flutter: 
  uses-material-design: true

