name: movie
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.12.0 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.3.8

  salomon_bottom_bar: ^3.1.0
  dio: ^4.0.0
  cookie_jar: ^3.0.1
  dio_cookie_manager: ^2.0.0
  html: ^0.15.0
  flutter_cupertino_settings: ^0.5.0
  webview_flutter: ^2.1.1
  flappy_search_bar_ns: ^2.0.2
  xml2json: ^5.3.1
  modal_bottom_sheet: ^2.0.0
  pull_to_refresh: ^2.0.0
  # cupertino_list_tile: ^0.2.0
  cached_network_image: ^3.1.0
  chewie: ^1.2.2
  video_player: ^2.2.5
  get_storage: ^2.0.3
  path_provider: ^2.0.6
  flutter_html: ^2.1.5
  clipboard: ^0.1.3
  wakelock: ^0.5.6
  auto_orientation: ^2.1.0
  desktop_webview_window: ^0.0.5
  bitsdojo_window: ^0.1.1+1
  url_launcher: ^6.0.12
  flutter_slidable: ^1.1.0

  waterfall_flow: ^3.0.2
  
  flutter: 
    sdk: flutter
  equatable: ^2.0.3

dev_dependencies:

  flutter_lints: ^1.0.0
  flutter_test: 
    sdk: flutter

  # flutter_launcher_name 与 flutter_launcher_icons 冲突
  # flutter_launcher_name:
  #   git:
  #     url: https://github.com/d1y/flutter_launcher_name

  flutter_launcher_icons: ^0.9.2

# flutter pub run flutter_launcher_name:main
flutter_launcher_name:
  name: "YY播放器"

flutter: 
  uses-material-design: true

  assets:
    - assets/data/nsfw.html
    - assets/data/source_help.txt
    - assets/images/fishtank.png
    - assets/images/image_faild.png
    - assets/data/play_tips.txt
    - assets/images/empty.png
    - assets/images/github_logo.png

    # before use node script/gen_source_create.js
    - assets/data/source_create.html

# flutter pub run flutter_launcher_icons:main
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "design/logo.png"