name: yyrelease
on:
  push:
    tags:
      - "release-v*"

jobs:
  release-to-gitHub:
    name: release
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.0.5"
          channel: "stable"
      - run: flutter pub get
      - run: flutter pub deps
      - run: flutter build apk --target-platform android-arm,android-arm64,android-x64 --split-per-abi

      # build all arch
      - run: flutter build apk --release

      - run: |
          flutter build ios --release --no-codesign
          cd build/ios/iphoneos
          mkdir Payload
          cd Payload
          ln -s ../Runner.app
          cd ..
          zip -r app.ipa Payload
      
      - run: |
          flutter config --enable-macos-desktop
          flutter build macos --release
          cd build/macos/Build/Products/Release
          zip -r movie.mac.zip movie.app/*

      - uses: softprops/action-gh-release@v1
        with:
          files: |
            build/app/outputs/flutter-apk/*.apk
            build/ios/iphoneos/app.ipa
            build/macos/Build/Products/Release/movie.mac.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}